CREATE INDEX IF NOT EXISTS idx_assistant_name ON assistant_name);
CREATE INDEX IF NOT EXISTS idx_conversation_id ON conversation_id),;
CREATE INDEX IF NOT EXISTS idx_knowledge_type ON knowledge_type);
CREATE INDEX IF NOT EXISTS idx_category ON category),;
CREATE INDEX IF NOT EXISTS idx_tags ON tags),;
CREATE INDEX IF NOT EXISTS idx_is_active ON is_active),;
CREATE INDEX IF NOT EXISTS idx_usage_count ON usage_count DESC);
CREATE INDEX IF NOT EXISTS idx_user_id ON user_id),;
CREATE INDEX IF NOT EXISTS idx_endpoint ON endpoint),;
CREATE INDEX IF NOT EXISTS idx_created_at ON created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_id ON user_id),;
CREATE INDEX IF NOT EXISTS idx_checklist_type ON checklist_type),;
CREATE INDEX IF NOT EXISTS idx_created_at ON created_at DESC);
CREATE INDEX IF NOT EXISTS idx_location ON location),;
CREATE INDEX IF NOT EXISTS idx_created_at ON created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_id ON user_id),;
CREATE INDEX IF NOT EXISTS idx_is_active ON is_active);
CREATE INDEX IF NOT EXISTS idx_user_id ON user_id),;
CREATE INDEX IF NOT EXISTS idx_created_at ON created_at DESC);
CREATE INDEX IF NOT EXISTS idx_source ON source),;
CREATE INDEX IF NOT EXISTS idx_created_at ON created_at DESC);
