[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
  "npm ci --production=false",
  "pip install pdfplumber"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"

[healthcheck]
path = "/health"
interval = 30
timeout = 60
