-- Add columns to existing feedback table
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS user_email VARCHAR(255);
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS request_description TEXT;
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS route VARCHAR(50);
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS response TEXT;
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS confidence DECIMAL(3,2);
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS is_useful BOOLEAN DEFAULT false;
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS feedback_type VARCHAR(50);
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS feedback_source VARCHAR(50) DEFAULT 'user';
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS slack_thread_ts VARCHAR(255);
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS slack_user_name VARCHAR(255);
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS slack_user_id VARCHAR(255);
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS slack_channel VARCHAR(255);
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS original_request_id UUID;
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;